app:
  title: Service Catalog
  baseUrl: http://backstageio-fargate-alb-2096651039.us-east-1.elb.amazonaws.com
  #baseUrl: http://localhost:3000

organization:
  name: NAVEX Global

backend:
  baseUrl: http://backstageio-fargate-alb-2096651039.us-east-1.elb.amazonaws.com
  #baseUrl: http://localhost:7000
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: sqlite3
    connection: ':memory:'
    #client: pg
    #connection:
    #  host:
    #    0.0.0.0
    #  port:
    #    5432
    #  user:
    #    "postgres"
    #  password:
    #    "password"
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      token:
        #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
        $env: GITHUB_TOKEN
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token:
    #     $env: GHE_TOKEN

proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generators:
    techdocs: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/tutorials/quickstart-app-auth to know more about enabling auth providers
  providers: 
    github:
      development:
        clientId: 
          #ce29efcc03782362321d
          000b8f411baf9cdbf337
        clientSecret:
          #618ef15f9f9332cb037d0cb47a60967d479ffd4f 
          e93be9beff576be73781356f2207260065472b4a

scaffolder:
  github:
    token:
      #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
      $env: GITHUB_TOKEN
    visibility: public # or 'internal' or 'private'

catalog:
  rules:
    - allow: [Component, System, API, Group, User, Template, Location]
  locations:
    - type: url
      target: https://github.com/tnwinc/api-docs/blob/backstage/as-built-apis/auth-service/catalog-info.yaml
      rules:
        - allow: [Template, API, Component]
    - type: url
      target: https://github.com/tnwinc/api-docs/blob/backstage/as-built-apis/coi/catalog-info.yaml
      rules:
        - allow: [Template, API, Component]
    - type: url
      target: https://github.com/tnwinc/api-docs/blob/backstage/as-built-apis/email/catalog-info.yaml
      rules:
        - allow: [Template, API, Component]
    - type: url
      target: https://github.com/tnwinc/api-docs/blob/backstage/as-built-apis/pt/catalog-info.yaml
      rules:
        - allow: [Template, API, Component]
    - type: url
      target: https://github.com/tnwinc/api-docs/blob/backstage/as-built-apis/userstore/catalog-info.yaml
      rules:
        - allow: [Template, API, Component]
