app:
  title: Scaffolded Backstage App
  #baseUrl: http://localhost:3000
  baseUrl: http://backstageio-fargate-alb-2096651039.us-east-1.elb.amazonaws.com

organization:
  name: My Company

backend:
  #baseUrl: http://localhost:7000
  baseUrl: http://backstageio-fargate-alb-2096651039.us-east-1.elb.amazonaws.com
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://backstageio-fargate-alb-2096651039.us-east-1.elb.amazonaws.com
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: sqlite3
    connection: ':memory:'
    #client: pg
    #connection:
    #  host:
    #    0.0.0.0
    #  port:
    #    5432
    #  user:
    #    "postgres"
    #  password:
    #    "password"
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      token: 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
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token:
    #     $env: GHE_TOKEN

proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generators:
    techdocs: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/tutorials/quickstart-app-auth to know more about enabling auth providers
  providers: 
    github:
      development:
        clientId: 2d8733efb35cb69b66e1
        clientSecret: 261341bac337fcc4a2a1b7804fc1d41a947d95e3

scaffolder:
  github:
    token: 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
    visibility: public # or 'internal' or 'private'

catalog:
  rules:
    - allow: [Component, System, API, Group, User, Template, Location]
  locations:
    - type: url
      target: https://github.com/tnwinc/api-docs/blob/backstage/as-built-apis/auth-service/catalog-info.yaml
      rules:
        - allow: [Template, API, Component]
    - type: url
      target: https://github.com/tnwinc/api-docs/blob/backstage/as-built-apis/coi/catalog-info.yaml
      rules:
        - allow: [Template, API, Component]
    - type: url
      target: https://github.com/tnwinc/api-docs/blob/backstage/as-built-apis/email/catalog-info.yaml
      rules:
        - allow: [Template, API, Component]
    - type: url
      target: https://github.com/tnwinc/api-docs/blob/backstage/as-built-apis/pt/catalog-info.yaml
      rules:
        - allow: [Template, API, Component]
    - type: url
      target: https://github.com/tnwinc/api-docs/blob/backstage/as-built-apis/userstore/catalog-info.yaml
      rules:
        - allow: [Template, API, Component]
